### ISSUE TITLE
Consider switching to mORMot-JWT

### ISSUE THREAD

**Issue by andrea-magni** [SchneiderInfosystems/FB4D#1]
Consider switching to https://github.com/andrea-magni/mORMot-JWT for JWT.
No more OpenSSL dependencies :-)

Sincerely

**Comment by SchneiderInfosystems** [comment]
Thank you Andrea for this input. I am very pleased that the author of the mars curiosity framework reviews my library!

In addition to extracting token's headers and claims, the FB4D requires for signature verification a method to handover a certificate retrieved from a Google Service that includes the public key. Is the mORMot-JWT able to handle that? 

This is the only reason for using OpenSSL in FB4D. FB4D is not establishing an SSL connection by using OpenSSL. For this purpose I'm using THTTPClient and its derived REST component.

**Comment by andrea-magni** [comment]
Hi Christoph,
I am always happy to look into interesting Delphi projects :-)

I am pretty sure mORMot has the capability to handle PKI verification and similar functionalities but, unfortunately, my knowledge of mORMot is limited and I can't be sure. And I can't even be sure the portion of mORMot I extracted (mORMot-JWT) contains what you would need. We may ask to Arnaud.

I am striving to remove OpenSSL dependency from MARS also (at the moment the only reason I am still using JOSE is for the Linux support as mORMot did not support Embarcadero Linux ARC-Enabled compiler... but the new 10.3 Embarcadero Linux compiler is NON-ARC :-D )

Sincerely
