### ISSUE TITLE
Firestore.PatchDocument fails for more than one field in the update mask

### ISSUE THREAD

**Issue by ChristophSchneiderTrihow** [SchneiderInfosystems/FB4D#10]
**Describe the bug**
There is a doublicate key exception when more than one fields shall be patched.
 
**Expectation**
The functiion shall work not only for one field but for multiple fields.

**Comment by SchneiderInfosystems** [comment]
Solved with commit 9c2ac4972fa033e8c01af293ff929e9775b69ec4
