### ISSUE TITLE
"Null" values non inserted in RT DB

### ISSUE THREAD

**Issue by larcspace** [SchneiderInfosystems/FB4D#101]
Hello All,

Thank you for this helpfull framework.
I do not know if it is a bug or not.

But all the "null" values of the attributes  of my simple JSONObjects have not been inserted in Firebase RealTime DB.
Is that normal ? Should I do something to force the "Null" values for each attribut to be inserted in RT DB?
I am using : RealTimeDB.Put (DBPath, LJSONObject, DBWritten, DBError);

I had other questions about using DBpath (Tstringdynarray) with programming. I do not know where to ask them. Can you help me about that too. 

Thank you.
Regards

**Comment by SchneiderInfosystems** [comment]
Where do you see that NULL nodes are supported in the RT-DB. In the Firebase console I don't see any possibility to insert such a node. Can you show me a DB with inserted NULL nodes?

For questions we have our discussion board:
https://github.com/SchneiderInfosystems/FB4D/discussions
Please check, if the questions is not already answered by checking the discussion board or in the wiki.

**Comment by larcspace** [comment]
Thanks for your answer.
To summarize, I would like to migrate a Postgresql table with 'Null' values to Firebase.
The problem is not the Null value of the attribute of an object as such, but the presence or not of the attribute that carries it in the database.

This is not possible. I will look for other ways. 
And this is not the place for this kind of question.

Thank you for your work and your useful framework 
Regards.
