### ISSUE TITLE
Memory leaks when creating a FirestoreListener 

### ISSUE THREAD

**Issue by ValidationFailed** [SchneiderInfosystems/FB4D#104]
**Describe the bug**
When at least one instance of a FirestoreListener is being created during a programs lifetime, Delphi reports memory leaks when closing the program with the setting `ReportMemoryLeaksOnShutdown =: true`.

**To Reproduce**
1. Launch the DempFB4D.exe program you've provided us with
2. Click _Anonymous Login_
3. Create a FirestoreListener (with `edtCollectionIDForFSListener.Text := "/"`)
4. Stop the FirestoreListener
5. Close the program

Doing just that, a window pops up which reports a couple of memory leaks.
The results of this issue are the same like it's been reported in #82 already. 
The difference is that the memory leaks don't occur when you **don't** stop the listener, but just close the program, which confirms the success of the fix for #82. :)

**Screenshots**
Creating and stopping a listener, as shown in the following image:
![grafik](https://user-images.githubusercontent.com/63789871/122763107-3fae8600-d29e-11eb-960b-de792cb4bb5d.png)
... results in: 
![grafik](https://user-images.githubusercontent.com/63789871/122763699-edba3000-d29e-11eb-9091-1040e24be65b.png)
... while starting a listener and closing the program without stopping it doesn't result in any memory leaks.

**Additional Info:**
 - OS: Windows 10, 32 Bit
 - FB4D-Version: 1.2.3.343

**Comment by SchneiderInfosystems** [comment]
Can you check FB4D-version 1.2.5.386. I made a correction for Delphi 10.4.2.

**Comment by ValidationFailed** [comment]
Oh, I'm sorry, it seems like I've been behind for a few versions..
Sorry for wasting your time and thanks a lot for your reply!
