### ISSUE TITLE
TFirebaseHelpers.DecodeTimeStampFromPUSHID — bug?

### ISSUE THREAD

**Issue by kazuser** [SchneiderInfosystems/FB4D#107]
Can't extract a right timestamp from the PushID `-MdS-Zc5Ed383SNy4jH3`:

`Edit2.Text := DateTimeToStr(TFirebaseHelpers.DecodeTimeStampFromPUSHID(Edit1.Text));`

![изображение](https://user-images.githubusercontent.com/3335273/124579214-bb006200-de70-11eb-8bd8-917ea900166e.png)

But [web function](https://stackoverflow.com/a/27910048/2689204) works fine:

![gif](https://user-images.githubusercontent.com/3335273/124580278-c6a05880-de71-11eb-9197-bd74b2ae7f55.gif)

**Comment by SchneiderInfosystems** [comment]
Thank you for reporting this issue, and sorry for the long delay in publishing the solution. I was in my vacancy ;)
