### ISSUE TITLE
In no Windows Console Application raise error I/O 105

### ISSUE THREAD

**Issue by e-martin** [SchneiderInfosystems/FB4D#108]
**Describe the bug**
When running an app that is not console application but is not visual (no forms displayed) the FB4D.Helpers.pas.TFirebase.Log try use writen raisin IO 105.

**To Reproduce**
1. Create VCL project not displaying forms and in DEBUG enabled
2. Connect to Firebase

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version Latest

**Additional context**
The workaround:

`class procedure TFirebaseHelpers.Log(msg: string);
begin
  if AppIsTerminated then
    exit;
{$IF Defined(FMX)}
  {$IFDEF LINUX}
  writeln(msg);  // Workaround for RSP-32303
  {$ELSE}
  FMX.Types.Log.d(msg, []);
  // there is a bug in DE 10.2 when the wrong method is calling?
  {$ENDIF}
{$ELSEIF Defined(VCL)}
  OutputDebugString(PChar(msg));
{$ELSEIF MSWINDOWS}
  OutputDebugString(PChar(msg));
{$ELSEIF CONSOLE} // CONSOLE directive added
  writeln(msg);
{$ENDIF}
  if Assigned(OnLog) then
    OnLog(msg);
end;
`

**Comment by kazuser** [comment]
https://github.com/SchneiderInfosystems/FB4D/discussions/103 — is it not the same?

**Comment by e-martin** [comment]
May be, my app its executed as service, no visual info.

**Comment by e-martin** [comment]
Ignore this thread, the $(FrameworkType) is the solution. 

My apologies.

**Comment by e-martin** [comment]
The $(FrameworkType) conditional define solve the problem.
