### ISSUE TITLE
Collection in Document

### ISSUE THREAD

**Issue by thanhapk** [SchneiderInfosystems/FB4D#11]
How to get collection is child of document ?
Thanks

**Comment by SchneiderInfosystems** [comment]
I assume you ask add a child document in Firestore, right?

For this purpose you have to extend the DocumentPath jst by a ChildName and its Id:

fDatabase.InsertOrUpdateDocument(['Collection', 'DocumentID' , 'Child', '123'], Doc,
    nil, OnFirestoreInsertOrUpdate, OnFirestoreError);

What surprises me a little bit is that it does not work without pass the Child-Id. I would have expected that without a child ID just one ID will be generated. I will check this point more in detail.

**Comment by SchneiderInfosystems** [comment]
For create a child was a generated ID you can use the CreateDocument function as follows:

fDatabase.CreateDocument(['Collection', 'DocumentID', 'Child'], nil, OnFirestoreCreate, OnFirestoreError)

**Comment by thanhapk** [comment]
Thanks for explain
