### ISSUE TITLE
Firestore error 404 

### ISSUE THREAD

**Issue by rzakfirst** [SchneiderInfosystems/FB4D#112]
Hello, this is to let you know that the firestore function no longer works; on the debug it displays an error in return 404.
Thank you!

**Comment by SchneiderInfosystems** [comment]
I cannot reproduce this issue.  I call every day several times FB Functions in different Firebase projects and I do not see any problem.

Please describe in detail what you try.

**Comment by RafaelWerner** [comment]
@rzakfirst check that the link mounted on line 75 of the `FB4D.Functions` file matches the link to your Firebase functions.

**Comment by rzakfirst** [comment]
> I cannot reproduce this issue. I call every day several times FB Functions in different Firebase projects and I do not see any problem.
> 
> Please describe in detail what you try.

Transaction failed: The project 196812833226 does not exist or it does not contain an active Cloud Datastore or Cloud Firestore database. Please visit http://console.cloud.google.com to create a project or https://console.cloud.google.com/datastore/setup?project=196812833226 to add a Cloud Datastore or Cloud Firestore database. Note that Cloud Datastore or Cloud Firestore always have an associated App Engine app and this app must not be disabled.

**Comment by SchneiderInfosystems** [comment]
Please describe more in detail when you see this message. I can still not reproduce the issue.

**Comment by SchneiderInfosystems** [comment]
Please check also the new function tab in the intro tab.
