### ISSUE TITLE
Get all documents of firestore in a var of type IFirestoreDocuments ( not only 20 first ).

### ISSUE THREAD

**Issue by macc2010** [SchneiderInfosystems/FB4D#128]
**Is your feature request related to a problem? Please describe.**
I would like to have a way to get all docs of a collection in a IFirestoreDocuments var.
For exmaple, imagine that you have 200 documents in a collection and I get them with this : 

```
var 
  Docs : IFirestoreDocuments;
begin
  Docs := FDatabase.GetSynchronous( aPath );
end;
```

I only get the 20 first documents. 

I would like to have something like this : 

```
var 
  Docs : IFirestoreDocuments;
begin
  Docs := FDatabase.GetSynchronous( aPath );
  if Docs <> nil then
  begin
    while Docs.MorePagesToLoad do
    begin
      Query := TQueryParams.CreateQueryParams.AddPageSize( 100 );
      Query.AddPageToken( Docs.PageToken );
      if not FDatabase.GetSynchronousAdd( Docs, aPath, Query ) then
        break;
    end;
  end;
end;
```

TFirestoreDocuments does not have any method to add documents to it. The TFirestoreDocuments are always added with the response filled as a request to Firestore.

**Describe the solution you'd like**
I have added 2 methods : 

```
function TFirestoreDatabase.GetSynchronousAdd(const aDocs: IFirestoreDocuments; Params: TRequestResourceParam; QueryParams: TQueryParams = nil) : Boolean;
var
  Request: IFirebaseRequest;
  Response: IFirebaseResponse;
begin
  Request := TFirebaseRequest.Create(BaseURI, '', fAuth);
  Response := Request.SendRequestSynchronous(Params, rmGet, nil, QueryParams);
  fLastReceivedMsg := now;
  if not Response.StatusNotFound then
  begin
    Response.CheckForJSONObj;
    aDocs.AddFromJSONDocumentsObj(Response);
    Result := True;
  end
  else
    Result := False;
end;
```

and this one : 

```
procedure TFirestoreDocuments.AddFromJSONDocumentsObj(Response: IFirebaseResponse);
var
  l, c: integer;
begin
  fSkippedResults := 0;
  fJSONObj := Response.GetContentAsJSONObj;
  if fJSONObj.Count >= 1 then
  begin
    l := length(fDocumentList);
    if fJSONObj.Pairs[0].JsonString.ToString = '"documents"' then
    begin
      if not(fJSONObj.Pairs[0].JsonValue is TJSONArray) then
        raise EFirestoreDocument.CreateFmt(rsInvalidDocArr, [fJSONObj.ToString]);
      fJSONArr := fJSONObj.Pairs[0].JsonValue as TJSONArray;
      SetLength(fDocumentList, l + fJSONArr.Count);
      for c := 0 to fJSONArr.Count - 1 do
        fDocumentList[l+c] := TFirestoreDocument.CreateFromJSONObj(fJSONArr.Items[c] as TJSONObject);
    end
    else
    begin
      SetLength(fDocumentList, l + 1);
      fDocumentList[l] := TFirestoreDocument.CreateFromJSONObj(fJSONObj);
    end;
  end;
  fServerTimeStampUTC := Response.GetServerTime(tzUTC);
  if not fJSONObj.TryGetValue<string>('nextPageToken', fPageToken) then
    fPageToken := '';
end;
```

**Comment by SchneiderInfosystems** [comment]
I have implemented your proposal with the follwong new method 

    function IFirestoreDatabase.GetAndAddSynchronous(var Docs: IFirestoreDocuments;
      Params: TRequestResourceParam; QueryParams: TQueryParams = nil): boolean;

To avoid memory leaks, some changes were made in `TFirestoreDocument`.

Please check my solution carefully and give me feedback here, as I don't have unit tests to back up this new method yet.

**Comment by macc2010** [comment]
> I have implemented your proposal with the follwong new method
> 
> ```
> function IFirestoreDatabase.GetAndAddSynchronous(var Docs: IFirestoreDocuments;
>   Params: TRequestResourceParam; QueryParams: TQueryParams = nil): boolean;
> ```
> 
> To avoid memory leaks, some changes were made in `TFirestoreDocument`.
> 
> Please check my solution carefully and give me feedback here, as I don't have unit tests to back up this new method yet.

Hello, 

I have tested the solution and works fine. 

Thank you very much. :-)
