### ISSUE TITLE
RunQuery with Sub Collection

### ISSUE THREAD

**Issue by fabriciolangermt** [SchneiderInfosystems/FB4D#13]
**Is your feature request related to a problem? Please describe.**
I need run RunQuery with a path concat in TFirebaseRequest URL

**Describe the solution you'd like**
update method RunQuery and RunQuerySynchronous and add a arg
DocPath and concat at  TFirebaseRequest.Create
`
  Request := TFirebaseRequest.Create(BaseURI + DocPath + METHODE_RUNQUERY, '', fAuth);
`

**Comment by fabriciolangermt** [comment]
i have this tree
{user_uid}/{employer_id}/{table_name}/{ID}/{DOCUMENT}
I need filter the DOCUMENT
DocPath  = {user_uid}/{employer_id}

**Comment by SchneiderInfosystems** [comment]
This is solved with commit 5cf7614521c19022a56b87a427e2ef8a33b0b7ef.
Please test the solution and give feedback! Thank you
