### ISSUE TITLE
How to get server timestamp from Firestore?

### ISSUE THREAD

**Issue by macc2010** [SchneiderInfosystems/FB4D#132]
Hello, 

I am looking for a way to get server timestamp to write it in a field of a document. 

I have seen that there is a example of it in the demo : 

    ServerTime := fRealTimeDB.GetServerVariablesSynchronous(cServerVariableTimeStamp, GetRTDBPath);

It uses Realtime database, but I do not use it, I use Firestore database, is there a way to get server timestamp from Firestore database?. 

Thank you.

**Comment by SchneiderInfosystems** [comment]
This does not seem to be a simple extension. After looking at the following StackOverflow discussion, I see that it requires a new _DocumentTransform_ command:
https://stackoverflow.com/questions/53943408/firestore-rest-api-add-timestamp

Unfortunately, I don't know now what the exact REST API call for DocumentTransform looks like. If you can help me with the research, I could implement the command afterward.

**Comment by macc2010** [comment]
In this stackoverflow question there is an answer for it : 

https://stackoverflow.com/questions/48610665/how-to-insert-server-timestamp-in-firestore-document-using-rest

https://stackoverflow.com/questions/57779415/cloud-firestore-rest-api-add-server-timestamp

Documentation : https://cloud.google.com/firestore/docs/reference/rest/v1/Write#FieldTransform 

It seems that instead of sending only fields, it is needed to send more data.

Thank you.

**Comment by macc2010** [comment]
I will do that, I will use UpdateTime as a temporally solution.

Thank you and best regards.

**Comment by SchneiderInfosystems** [comment]
Solved in version 1.5.0.506
