### ISSUE TITLE
Implement transactions in the library.

### ISSUE THREAD

**Issue by macc2010** [SchneiderInfosystems/FB4D#136]
**Is your feature request related to a problem? Please describe.**
Now I have a project where I need to use transactions and by several reasons, I cannot implement the transactions in a cloud function.

**Describe the solution you'd like**
I would like to have a RunTransaction method in the database object to be able to read data in a transaction and finally write/delete documents in the Firestore database.

Are there plans to make this change soon?.

I have seen that other official sdk implementations in github ( like php, go ... etc ), make it using the begintran and commit rollback keywords calling the appropiate rest apis, and as you told that you had found a way to call these methods in the documentation I was asking me if there were any advances in this direction. 

Thank you.

**Comment by SchneiderInfosystems** [comment]
This feature request is already on the wish list. I have been working on this issue for a while and initially did not find a solution that works for WriteTransactions. ReadTransaction has been around for quite some time.
In the meantime, I have seen a solution that could work. But currently, I don't have the time. to implement this complex solution. It will be autumn until I can present a solution here.

**Comment by macc2010** [comment]
Thank you very much.

**Comment by SchneiderInfosystems** [comment]
Solved late in version 1.5.0.506
