### ISSUE TITLE
Implement all features in TStructuredQuery

### ISSUE THREAD

**Issue by fabriciolangermt** [SchneiderInfosystems/FB4D#14]
unit FB4D.Firestore

**Is your feature request related to a problem? Please describe.**
orderBy, startAt, endAt, offset and limit not implemented

**Describe the solution you'd like**
implement orderBy, startAt, endAt, offset and limit options in TStructuredQuery

**Comment by SchneiderInfosystems** [comment]
Thank you for this valuable point.
In the meantime, I have implemented at least orderBY. 
See my commits from today and try also the new RunQuery function in the DemoFB4D Project.

**Comment by SchneiderInfosystems** [comment]
Now, all methods including the select are implemented. Check Commit 3855f27515e5f7179ae4e6e38a81229c1b972bc5
and test
