### ISSUE TITLE
TFirestoreDocuments.CreateFromJSONArr on Query offset and limit (second page)

### ISSUE THREAD

**Issue by fabriciolangermt** [SchneiderInfosystems/FB4D#15]
**Is your feature request related to a problem? Please describe.**
TFirestoreDocuments.CreateFromJSONArr
where Query return second page of limit and offset, first node return readTime, and second and others nodes, return DOCUMENT node

**Describe the solution you'd like**
hard coded
`
for c := 0 to fJSONArr.Count - 1 do
  begin
    Obj := fJSONArr.Items[c] as TJSONObject;

    if (fJSONArr.Count = 1) and (Obj.Pairs[0].JsonString.Value = 'readTime') then
      // Empty [{'#$A'  "readTime": "2018-06-21T08:08:50.445723Z"'#$A'}'#$A']
      SetLength(fDocumentList, 0)
    else if (fJSONArr.Count = 1) and (Obj.Pairs[0].JsonString.Value <> 'document') then
      raise EFirestoreDocument.CreateFmt(rsInvalidDocNode,
        [Obj.Pairs[0].JsonString.ToString])
    else if (fJSONArr.Count = 1) and not(Obj.Pairs[0].JsonValue is TJSONObject) then
      raise EFirestoreDocument.CreateFmt(rsInvalidDocNode,
        [rsNotObj + Obj.ToString])
    else if (Obj.Pairs[0].JsonString.Value = 'document') then
    begin
      SetLength(fDocumentList, length(fDocumentList) + 1);
      fDocumentList[length(fDocumentList) - 1] :=
        TFirestoreDocument.CreateFromJSONObj(
          Obj.Pairs[0].JsonValue as TJSONObject);
    end;
  end;
`

**Describe alternatives you've considered**
try if exists documents

**Comment by SchneiderInfosystems** [comment]
When I have added limit and offset method I saw this issue too. Its is solved since commit 3855f27515e5f7179ae4e6e38a81229c1b972bc5
