### ISSUE TITLE
[DCC Error] FB4D.Interfaces.pas(1025): E2003 Undeclared identifier: 'OnAnnotate'

### ISSUE THREAD

**Issue by YILDIRIMBEY** [SchneiderInfosystems/FB4D#156]
I'm getting this error, it says there are missing definitions, how can I fix it?

[DCC Error] FB4D.Interfaces.pas(1025): E2003 Undeclared identifier: 'OnAnnotate'
[DCC Error] FB4D.Interfaces.pas(1025): E2035 Not enough actual parameters
[DCC Fatal Error] FB4D.Authentication.pas(37): F2063 Could not compile used unit 'FB4D.Interfaces.pas'
Failed
Elapsed time: 00:00:07.0

**Comment by SchneiderInfosystems** [comment]
I cannot reproduce this issue. Please inform me, which project you want build? 
Please check before if you have the current code from GitHub.
