### ISSUE TITLE
Inform in IRealTimeDB.ListenForValueEvents if a automatic token refresh was done

### ISSUE THREAD

**Issue by ChristophSchneiderTrihow** [SchneiderInfosystems/FB4D#16]
**Is your feature request related to a problem? Please describe.**

When the Real Time DB listener runs longer than an hour the authentication token needs to be renewed. This is done automatically by the listener but the caller does not get an event. 

**Describe the solution you'd like**

In Addition, to ListenEvent, OnStopListening, and OnError a new OnTokenRefresh is required.

**Comment by SchneiderInfosystems** [comment]
Solved in commit ccc94be0e5fb5d22da148861e090b34491e3154d
