### ISSUE TITLE
Firebase querying with partial string match

### ISSUE THREAD

**Issue by RaySa74** [SchneiderInfosystems/FB4D#17]
thanks for creating this for delphi :)

i want to do something like this with the database 
SELECT userid 
FROM tablename 
WHERE username LIKE 'abc%'

can we do it using you code?? i found this article in stackoverflow where they suggest to do something like this  yourRef.orderByKey().startAt("abc").endAt("abc\uf8ff") 

can you please help, thanks ray

https://stackoverflow.com/questions/46460825/firebase-querying-with-partial-string-match

**Comment by SchneiderInfosystems** [comment]
Your question concerns the Firebase Realtime Database?
The RT DB does not support data filtering on server side (like the Firestore offers with RunQuery). The mention solution from Stackoverflow is based on client side filtering using the power of Java lib for searching in a JSON Tree. FB4D does currently not offer such capabilties.
You have to implement a such search for the fetched JSON tree by yourself.
Generally, in Firebase the structure of the JSON tree has to be defined in order that often used writing and reading acess are as fast as possible. If the requested like-query is often requested you have to think how you can de-normalize the field username that you shortly can access the requested user data. Pherhaps you can build a first structure under the path /username/* to retrieve the UserID by all expected variants of the username while you build a second structure to retrieve all data of the user under the path /userid/*.
Hope this idea is helpful for you.

**Comment by RaySa74** [comment]
thanks for the quick reply.
i was trying to get the info from the Firestore Database, i noticed from your wiki https://github.com/SchneiderInfosystems/FB4D/wiki/FB4D-Reference-IStructuredQuery
that you have StartAt and EndAt for IStructuredQuery.

can you use RunQuery to get a partial string Query from the db? thanks for your help i'm new to this.
ray

**Comment by SchneiderInfosystems** [comment]
On Firestore Database you can use RunQuery that allows you to combine a where clause with order-by and StartAt/EndAt cursor operation for filtering on server side. For such application Firestore is much better than Firebase RT Db. 
Have a look at the sanple app Intro where the use of RunQuery is demonstrated.

**Comment by RaySa74** [comment]
I downloaded FB4D and I have been working with it for a week now (Very helpful and easy to understand). i looked into how to create a RunQuery for finding a sub string in a fftString Field but I could not figure it out.

Can you please provide a sample code where you can Query for a sub string in Firestore db?

Also in 2018 they added the ability to query for elements within arrays using the new "array-contains" feature.  Is this available in FB4D. (if you can provide sample code will be great)

https://firebase.googleblog.com/2018/08/better-arrays-in-cloud-firestore.html

thank you for you great work for the Delphi community 
ray

**Comment by SchneiderInfosystems** [comment]
You can found a sample here:
FB4D/Samples/Intro/FB4D.DemoFmx.pas
in _TfmxFirebaseDemo.btnRunQueryClick_.

I have improved the wiki page https://github.com/SchneiderInfosystems/FB4D/wiki/FB4D-Reference-IQueryFilter.

If you miss an aspect in the wiki or the Intro Demo project do not hesitate to give me a proposal of a better description. Thank you!
