### ISSUE TITLE
Set an array using a string when using AddOrUpdateField

### ISSUE THREAD

**Issue by RaySa74** [SchneiderInfosystems/FB4D#18]
When you add an Array using AddOrUpdateField, can you set the array using a string? (see sample below). Thanks ray
jValue: TJSONValue;
st: string;
      st := '{"name", "John Smith", "age"}';
      jValue := TJSONObject.ParseJSONValue(st);
      Doc.AddOrUpdateField(TJSONObject.SetArray('MyArr', jValue));

**Comment by SchneiderInfosystems** [comment]
Please check the Intro sample. In the methode TfmxFirebaseDemo.btnInsertOrUpdateDocumentClick your question is implemented. Also the referencce guide for IDatabase has some explanation.
