### ISSUE TITLE
Can we Query for elements within arrays?

### ISSUE THREAD

**Issue by FerasDaya** [SchneiderInfosystems/FB4D#19]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by FerasDaya** [comment]
Is there a way to Query for elements within arrays using ‘array-contains" feature, this is very helpful in finding documents with certain keywords attached to it.

Thanks

https://firebase.google.com/docs/firestore/query-data/queries#array_membership

**Comment by SchneiderInfosystems** [comment]
For this purpose you have to use the RunQuery method with a IStructuredQuery built by using TWhereOperator.woArrayContains.
Is this htip helpfull?

**Comment by SchneiderInfosystems** [comment]
See also my new explanation in https://github.com/SchneiderInfosystems/FB4D/wiki/FB4D-Reference-IQueryFilter

If you miss an aspect in the wiki do not hesitate to give me a proposal of a better description. Thank you!
