### ISSUE TITLE
Stopping the Event Handler deletes the data in the RealTime db.

### ISSUE THREAD

**Issue by RaySa74** [SchneiderInfosystems/FB4D#20]
Hi
I created multiple Nodes using “Put” command in the lib demo app, then activated ‘Notify Event Handler’ in the “Scan Real Time DB Event” tab. When I stop the event handler the nodes I created are deleted in the RealTime db?! I want to delete them manually not automatically when I stop the event handler.

Is there a way to not delete the nodes automatically in the RealTime db when I Stop the Event Handler?
thanks

**Comment by SchneiderInfosystems** [comment]
Hi
This behavior is described in detail here: 
https://github.com/SchneiderInfosystems/FB4D/wiki/FB4D-Reference-IFirebaseEvent
To improve this situation, please vote in Embarcadero quality central for this RSP-20827.

To prevent the deletion of the entire node, pass a _NodeName_ in the method _StopListening_.
