### ISSUE TITLE
Encoding problem with Real Time DB

### ISSUE THREAD

**Issue by RaySa74** [SchneiderInfosystems/FB4D#21]
Hope all is well, thanks again for you great work
Using the Firebase Lib Demo, I added Node to the Real Time DB, but the Value in the node contains Arabic letters. When I go to “Scan Real Time DB Event” tab and then activate “Notify Event Handler” 
The node with Arabic letters are displayed using JsonUTF8 (\u00D8\u00B0\u00D9\u2021\u00D8) 
I tried using TJSONValue to get the Arabic letters back but it’s not working 
     LJSONValue:=TJSONObject.ParseJSONValue(TEncoding.UTF8.GetBytes(order_info.GetValue('Name').ToJSON),0);
Showmessage(LJSONValue.ToString);
Can you please help; it looks like the function fRealTimeDB.ListenForValueEvents has a problem when getting the Arabic letters for google 
Thanks

**Comment by SchneiderInfosystems** [comment]
Both FB4D and Firebase support Unicode. Arabic letters are special Unicode point sets. 
The only issue occurs, when you display a string value out of the resulting JSON tree, you must handle this TJSONValue as TJSONString for a proper conversion from UTF8 to string. 
In the Intro application, I have considered now this point in the method ShowRTNode - see my last commit. In the method OnRecData, I list the content of the returned  JSONObject still in JSON notation for the sake of simplicity. In your application, you have to interpret the JSON Object according to your expected object structure. 
Hope this explanation gives you the right insights to handle the returning JSONObject correctly.
