### ISSUE TITLE
Unable to Load OpenSSL Error on android 

### ISSUE THREAD

**Issue by RaySa74** [SchneiderInfosystems/FB4D#23]
i am testing the new delphi 10.3.2 so i tried to load the "Firebase Lib Demo" on my android phone.
but when the app opens and i fill in the info needed then i click "Anonymous Login" i get this error

(Sign in with email for ray23@gmail.com failed : [RSA] Unable to Load OpenSSL Libraries)

please help
thanks

**Comment by SchneiderInfosystems** [comment]
I forgot to remove the conditional compiling switch TOKENJWT from the Android and iOS configuration. Just remove this switch from the base configuration in the project settings or wait until next week when I can fix this issue.

**Comment by RaySa74** [comment]
When you remove TOKENJWT from Conditional defines, will get a compiler error when you Build for Android
[DCC Error] FB4D.OAuth.pas(35): E2003 Undeclared identifier: 'ITokenJWT'
[DCC Error] FB4D.OAuth.pas(94): E2003 Undeclared identifier: 'ETokenJWT'

**Comment by SchneiderInfosystems** [comment]
Try to rebuild

**Comment by RaySa74** [comment]
I tried rebuilding the project not working :( 
I noticed this problem also When you released your new version I took the new source files to my old project then I cleaned the project and recompiled and I got the same errors, I look in “Conditional defines” and I noticed you added TOKENJWT. So I added it to my old project then it compiled. But it seems it created the OpenSSL bug!?

**Comment by ismaaelvale** [comment]
When I log in to the Demofb4d sample app, I get the error: sign in with email for email@email.com failed: [OpenSSL] Unable to load OpenSSL libraries.

What to do?

Delphi 10.3 Rio

**Comment by SchneiderInfosystems** [comment]
@ismaaelvale: I assume you do not want to run the Demofb4d on Android? So please do not add any question to a solved issue without concern to this issue. To your question: Pls read this: https://github.com/SchneiderInfosystems/FB4D/wiki/Getting-Started-with-FB4D#install-openssl
