### ISSUE TITLE
Problem with Get Storage 

### ISSUE THREAD

**Issue by RaySa74** [SchneiderInfosystems/FB4D#24]
When you set the edtStoragePath for imgs/ then you use btnUploadSynch, the folder will be created and the file uploaded successfully, but when you use btnGetStorageSynch an error occurs (Invalid Http Method/url Pair.) !?

thanks

**Comment by SchneiderInfosystems** [comment]
I cannot reproduce this issue. It should be solved with commit "https://github.com/SchneiderInfosystems/FB4D/commit/781efefa89a54f35e72b35dcd42c7ce085344511".
