### ISSUE TITLE
SendRequestSynchronous

### ISSUE THREAD

**Issue by mathanse47** [SchneiderInfosystems/FB4D#29]
Hey , i a new o delphi and i am trying to  use your demo, but when a i run, i get: FB4D.Oauth there is no overload version of "SendRequestSynchronous" that can be called with this arguments. I really don't now what to do.

**Comment by mathanse47** [comment]
I 'v trying use the 10.3 ... on 10.2 works fine

**Comment by SchneiderInfosystems** [comment]
Do you use the newest update of 10.3.2? I remember there was a Delphi RTL issue which is fixed now and I have removed the former workaround for 10.3.1. See this commit: https://github.com/SchneiderInfosystems/FB4D/commit/953dd2907a544ac8e9f0f4721f3c6d07aa478bd2

**Comment by mathanse47** [comment]
I think that is 10.3.1 ( Embarcadero® Delphi 10.3 Version 26.0.32429.4364 ). I do that and i got like 12 more of the same error lol. So is just put the first value on a variable  ?

**Comment by SchneiderInfosystems** [comment]
You can either revert all the source files by yourself or you can go back to this release which was still working on De 10.3.1:
https://github.com/SchneiderInfosystems/FB4D/releases/tag/0.9.4
Or better try to update to De 10.3.2.
