### ISSUE TITLE
RTDB Get method deleting child nodes automaticlly

### ISSUE THREAD

**Issue by AmoStack** [SchneiderInfosystems/FB4D#32]
whenever i try to use `Get` method it erases all nodes and writes timestamp in database.
this is the code i am using:

     // Clicking on btnLogin
    procedure TForm3.BtnLoginClick(Sender: TObject);
    begin
      if not Assigned(fConfig) then
        fConfig := TFirebaseConfiguration.Create(cApiKey, cId);
      fConfig.Auth.SignInWithEmailAndPassword(Edit1.Text, Edit2.Text,
        onUserResponse, onError);
    end; 
    
    //Log In Success
    procedure TForm3.onUserResponse(const Info: string; user: IFirebaseUser);
    begin
      UID := user.UID;
      pass := Edit2.Text;
      Email := user.Email;
      fConfig.RealTimeDB.GetServerVariables(cServerVariableTimeStamp, GetRTDBPath,
        onServerStamp, onError);
      Text1.Text := UID;
    end; 
    
    //Getting ServerTime for Usage
    procedure TForm3.onServerStamp(const ServerVar: string; Val: TJSONValue);
    var
      ST: int64;
    begin
      ST := StrToInt64(Val.Value);
      sDate := TTimeZone.Local.ToLocalTime(UnixToDateTime(ST div 1000));
      SaveUser;
      UpdateLoginStatus;
    end; 
    
    //Trying to get data to use but is not getting at all 
    procedure TForm3.UpdateLoginStatus;
    begin
      fConfig.RealTimeDB.Get(GetRTDBPath, onGetResponse, onError);
    end; 
    
    //updating LoggedIn Status
    procedure TForm3.onGetResponse(ResourceParams: TRequestResourceParam;
      Val: TJSONValue);
    var
      sValue: TJSONObject;
    begin
      ShowRTNode(ResourceParams, Val);

      //Below Will be used later once data is received 
      {sValue := TJSONObject.Create;
      try
        sValue.AddPair('LoggedIn', 'True');
        fConfig.RealTimeDB.Patch(GetRTDBPath, sValue, ShowRTNode, onError);
      finally
        sValue.Free;
      end;}
    end;

when i try to get Data it deletes all the nodes and then creates a timestamp in path.

Why so ?

**Comment by SchneiderInfosystems** [comment]
This is a side effect of `RealTimeDB.GetServerVariables(cServerVariableTimeStamp, GetRTDBPath..)`. This function does not return the time stamp only. It writes the time stamp also in the node addressed by ResourceParams. Please read also the description in the wiki here:
https://github.com/SchneiderInfosystems/FB4D/wiki/FB4D-Reference-IRealTimeDB#get-a-server-variable

**Comment by AmoStack** [comment]
okay now so using timestamp node so doesn't matter now. thank you.
