### ISSUE TITLE
firebase function no query parameters recevied ?

### ISSUE THREAD

**Issue by AmoStack** [SchneiderInfosystems/FB4D#33]
HI again,

I am trying to call my firebase functiono with parameters `key and uid` but the library is not sending any parameters in request.
here is the code i tried.

     params := TJSONObject.Create;
     params.AddPair('uid', UID);
     params.AddPair('key', '95871234');
     fConfig.Functions.CallFunction(onFucntion, onError, 'doLogin', params);

but in the firebase log console i found that the library does not sends any params ? why and one more thing in your firebase functions class you're readding the params object ot another object :

    procedure TFirebaseFunctions.CallFunction(OnSuccess: TOnFunctionSuccess;
      OnRequestError: TOnRequestError; const FunctionName: string;
      Params: TJSONObject);
    var
      Request: IFirebaseRequest;
      Data: TJSONObject;
    begin
      fOnSucess := OnSuccess;
      fOnError := OnRequestError;
      Data := TJSONObject.Create;
      try
        Data.AddPair('data', Params);
        Request := TFirebaseRequest.Create(BaseURL,
          Format(rsFunctionCall, [FunctionName]), fAuth);
        Request.SendRequest([FunctionName], rmPost, Data, nil, tmBearer,
          OnResp, OnRequestError);
      finally
        Data.Free;
      end;
    end; 

and you haven't mentioned it in any document.

how to correctly send query params ?

**Comment by SchneiderInfosystems** [comment]
I do it exactly in the same way you have done it and it works for my function. Yes, The parameters need to be encapsulated into a JSON object {data: {param1: "test"}}.

Can you show the function and how you retrieve the parameters? I assume your problem is at the function side.

**Comment by AmoStack** [comment]
here it the full function

    exports.doLogin = functions.https.onRequest((req, res) => {
      
      const sUid = req.query.uid;
      const sKey = req.query.key;
      console.log(sUid +' '+sKey);
    
      admin.database().ref('/users/' + sUid).once('value')
        .then((snapshot) => {
              
          const data = snapshot.data.val();
          const fKey = data.key;
          const isKind = data.Donation;
          const logState = data.LoggedIn;
    
          switch (logState) {
            case "false": {
              if (isCosd === 'true') {
                res.status(200).json({ 'result': 'preLogin' })
                break;
              } else {
                res.status(200).json({ 'result': 'Login' });
                break;
              }
            }
            case "true": {
              if (sKey === fKey) {
                if (isCosd === 'true') {
                  res.status(200).json({ 'result': 'osLogin' });
                  break;
                } else {
                  res.status(200).json({ 'result': 'Login' });
                  break;
                }
              } else {
                res.status(200).json({ 'result': 'diffrent_system' });
              }
            }
          }
          return null;
        })
        .catch(error => {
          console.log(error);
          res.status(404).send(error);
        })
    })

**Comment by SchneiderInfosystems** [comment]
Why not simple?

    const sUid = req.uid;  
    const sKey = req.key;

**Comment by AmoStack** [comment]
nor work for me i have to use

`const sUid = res.body.data.uid;`

**Comment by SchneiderInfosystems** [comment]
Did you change to OnCall?

**Comment by SchneiderInfosystems** [comment]
In this case, I will do more research to give a simple example.

**Comment by AmoStack** [comment]
Whoops no i didn't sorry.
but there is other thing i found which is weird as hell to me.
i return json response to the request like this:
` res.status(200).json({ result : {'result': 'Login'});`
but when i try to send multiple values it didn't receives the other one :
` res.status(200).json({ result : {'result': 'Login', 'cdn':'vars'});`

**Comment by SchneiderInfosystems** [comment]
I will soon show an example of a javascript function based on OnCall which handles the parameters correctly.

**Comment by SchneiderInfosystems** [comment]
Write your function `doLogin` as follows:

    exports.doLogin = functions.https.onCall(async (data, context) => {
       const sUid = data.uid;  
       const sKey = data.key;
       console.log('doLogin called with UID=' + sUid + ', Key=' + sKey);
      ...
       return { result: 'ok' };
    });

So you can call it from your application like that:

     params := TJSONObject.Create;
     params.AddPair('uid', UID);
     params.AddPair('key', '95871234');
     res := fConfig.Functions.CallFunctionSynchronous('doLogin', params);
     if res.GetValue<string>('res') = 'ok' then
        ...

I will add this explanation to the description in the Wiki. Thank you for your review of the Wiki!

**Comment by SchneiderInfosystems** [comment]
See also the new integration test for FBFunction added in 319fc1c3f42b93d333cfa8cd983008a3c85c57e1
