### ISSUE TITLE
No page "Synchronous vs Asynchronous Method Calls" in Documentation

### ISSUE THREAD

**Issue by SergioDragon** [SchneiderInfosystems/FB4D#37]
In documentation https://github.com/SchneiderInfosystems/FB4D/wiki/Getting-Started-with-FB4D#write-your-first-json-node there is a link "Synchronous vs Asynchronous Method Calls" to https://github.com/SchneiderInfosystems/FB4D/wiki/Synchronous-vs-Asynchronous-Method-Calls , but no such page.

**Comment by SchneiderInfosystems** [comment]
Thank you for this hint! I have corrected now the page.
