### ISSUE TITLE
Problems with RealTimeDB listen for value event

### ISSUE THREAD

**Issue by RaySa74** [SchneiderInfosystems/FB4D#39]
Hi
Having some problems with RealTimeDB listen for value event.
To get the values from RealTimeDB I have to run this command two or three time to get the values??

  if not CheckAndCreateRealTimeDBClass(memScans) then
exit;
  fFirebaseEvent := fRealTimeDB.ListenForValueEvents
    (SplitString(edtRTDBEventPath.Text.Replace('\', '/'), '/'), OnRecData,
    OnRecDataStop, OnRecDataError);

Some time I get this error list below then I get the values from the RealTimeDB, can you please help why not from the first time I send the command fRealTimeDB.ListenForValueEvents I get the values from the RealTimeDB?? Is there a limit from google with the size of the data received?? 

7:10:38 PM: Event handler started for RTimeDB_store1
7:10:39 PM: +Error in Exception in event parser: Stream read error
7:10:39 PM: +Error in Exception in event parser: Stream read error
7:10:39 PM: +Error in Exception in event parser: Stream read error
7:10:39 PM: +Error in Exception in event parser: Stream read error
---------
7:10:39 PM: put[RTimeDB_store1] = {"path":"\/","data":{"04-01-20_17-07-38-399":{…..(deleted the code its long)

**Comment by SchneiderInfosystems** [comment]
You should receive immediately a first OnRecData after installing a listener for a given node.
What I do not understand is, why you do this:
`edtRTDBEventPath.Text.Replace('', '/')`
Can you test with constant data ['path1', 'path2'] to ensure that this has no impoact.
There is no limitation in size for the receiving stream as I know. Is your node such big?

Check this simple example:
https://github.com/SchneiderInfosystems/FB4D/blob/master/Samples/RTDB_PerUserReadWrite/FB4D.PerUserReadWrite.pas

**Comment by RaySa74** [comment]
hi
i changed it to 
  fFirebaseEvent := fRealTimeDB.ListenForValueEvents (['', edtRTDBEventPath.Text], OnRecData,
    OnRecDataStop, OnRecDataError,nil);
	
but i am still having the same problem of running the code two or three time to get the data from RealTimeDB , please see the error below it changed. also i noticed when i change the path of edtRTDBEventPath.Text to a smaller data set in the RealTimeDB i get the
data from the first try?? i think the problem is related to the size of the data  
thanks
	

9:59:17 PM: Event handler started for ,RTimeDB_store1
9:59:18 PM: +Error in Exception in event parser: Invalid stream read count: 0 - 4603 (C:\Users\Da\Documents\Testing_sys\system\FB4D.RealTimeDB.pas, line 697)
9:59:18 PM: +Error in Exception in event parser: Invalid stream read count: 3800 - 4603 (C:\Users\Da\Documents\Testing_sys\system\FB4D.RealTimeDB.pas, line 697)
9:59:43 PM: +Error in Exception in event parser: Stream read error

**Comment by SchneiderInfosystems** [comment]
Do you have updated your repo the newest GitHub commit? There was an issue in this area in the past: 1f8ecb77e9d08276396fb3132282bfd4298a3be7
On which platform you see this problem?   
Can you reproduce this issue with the CloudClipboard sample project too?
Because this example demonstrates with Images also the usage of large nodes.

**Comment by RaySa74** [comment]
thanks
i downloaded 6th Prerelease of FB4D and the fix was not added, but when i downloaded FB4D from the main github, now everything is working as expected. 
thank you very much
