### ISSUE TITLE
Security

### ISSUE THREAD

**Issue by gorepj** [SchneiderInfosystems/FB4D#4]
Can you please tell me how best to implement security programmatically using FB4D.
RealtimeDatabase
I'm storing User data underneath a node where the name of the node = the User's email address.  How can I restrict access programmatically so that only a User with the correct email address can read and write data to that node?
Storage
Likewise, I'm storing documents within a folder where the folder name = the User's email address.
How can I restrict access programmatically  so that only a User with the correct email address can read and write documents to that folder?

**Comment by SchneiderInfosystems** [comment]
You have to learn the concept of access rules of Firebase.
A good starting point is in the Firebase documentation:
[firebase.google.com/docs/database/security](https://firebase.google.com/docs/database/security/?authuser=0)

I can also recommend to play and analyse the second sample project [CloudClipboard/MainFmx.pas](https://github.com/SchneiderInfosystems/FB4D/blob/master/Samples/CloudClipboard/MainFmx.pas).
In this project the recommended access rules solves exactly your request.

See the hint to the permission error:
Before you can write into the real time database add the following text in the Firebase console as rule for the Realtime Database:

`{`
`    "rules": {"cb": "$uid": {` 
`        ".read": "(auth != null) && (auth.uid == $uid)",`
`        ".write": "(auth != null) && (auth.uid == $uid)" }}}}`

Where as each user has it own root node at `/cb/<UID>/`.

**Comment by SchneiderInfosystems** [comment]
To help other developers on this topic I added an separate chapter in the _getting started wiki page_
[Wiki/Getting-Started-with-FB4D#security-in-firebase-setup-the-access-rules](https://github.com/SchneiderInfosystems/FB4D/wiki/Getting-Started-with-FB4D#security-in-firebase-setup-the-access-rules)

@gorepj : Can you review this chapter. Is that clear and understandable written? Does it help a new user to qucikly find the right answers?
