### ISSUE TITLE
TFirestoreDatabase.GetSynchronous response with an Exception instead of nil when no document is available

### ISSUE THREAD

**Issue by ChristophSchneiderTrihow** [SchneiderInfosystems/FB4D#40]
**Describe the bug**
The TFirestoreDatabase.GetSynchronous method has another reaction then the asynchronous TFirestoreDatabase.Get when a requested path does not point to an existing node.

**To Reproduce**
1. Call `TFirestoreDatabase.GetSynchronous` for a nonexistent path.
2. Check the response

**Expected behavior**
As a result of the method `TFirestoreDatabase.GetSynchronous` nil is expected.

**Real behavior**
An exception of EFirebaseResponse is thrown.

**Additional context**
All platforms are affected

**Comment by SchneiderInfosystems** [comment]
This solved with commit  8267742d5f0370389e8062643d0145888882d304.
