### ISSUE TITLE
How to create query to Firestore with "AND" conditions ? 

### ISSUE THREAD

**Issue by SergioDragon** [SchneiderInfosystems/FB4D#42]
Dear FB4D Creator, 
please advise how with FB4D to create query to Firestore, that contains 'AND' in WHERE condition?

I need to select from a collection (AllUsers) all documents that have fields 'user_email'=specific_email AND 'user_active'=1.

Something like in python will be 

AllUsers.where(u'user_email', u'==', specific_email).where(u'user_active', u'==', 1)

I'm trying with FB4D following, however it doesn't' work correct, because applying only the last condition ('user_active'=1), and removing first condition ('user_email'=specific_email):

```
fDatabase.RunQuery(
  TStructuredQuery.CreateForSelect( ['user_email','user_active', 'company_id','department_id', 'user_role'] )
    .Collection( AllUsers )
    .QueryForFieldFilter(
        TQueryFilter.StringFieldFilter('user_email', woEqual,
                             specific_email ))
    .QueryForFieldFilter(
        TQueryFilter.IntegerFieldFilter('user_active', woEqual,
                             1 ))
      .Limit( 5 )
        ,
      OnDocumentsOk, OnRequestError, Query);
```

Please advise, how to make 'AND in WHERE in a proper way?

**Comment by SchneiderInfosystems** [comment]
Do you read this page:
https://github.com/SchneiderInfosystems/FB4D/wiki/FB4D-Reference-IStructuredQuery
The second example shows exactly your questions:

`Database.RunQuery(
  TStructuredQuery.CreateForCollection('MyCollection').QueryForCompositeFilter(
    coAnd,
    [TQueryFilter.StringFieldFilter('MyAttribute', woEqual, 'red'),
     TQueryFilter.BooleanFieldFilter('MyVal', woLessThan, 5.0)]),
  OnDocuments, OnRequestError)`
