### ISSUE TITLE
2 or more simultaneous async RunQuery calling only the last passed TOnDocuments procedure

### ISSUE THREAD

**Issue by SergioDragon** [SchneiderInfosystems/FB4D#43]
While developing Android app using FB4D code, I faced with the problem that makes Android app functioning incorrectly.
Stuck on this problem now.

I run 2 asynchronous queries, each has its own TOnDocuments and TOnRequestError callback procedures:

`
fDatabase.RunQuery([ 'Companies', a_company_id ],
    TStructuredQuery.CreateForSelect(['department_name'])
    .Collection('departments') ,
    OnGetDepartmentsOK, OnGetDepartmentsError, NIL);
`
`//... a few lines of code here ...`
`
fDatabase.RunQuery([ 'Companies', a_company_id ],
    TStructuredQuery.CreateForSelect(['location_name','latitude','longitude','distance'])
    .Collection('locations') ,
    OnGetLocationsOK, OnGetLocationsError, NIL);
`

WHAT IS WRONG:

For both queries results called TOnDocuments procedure that was passed as argument in the LAST called RunQuery.
I.e., for 'departments' query called **OnGetLocationsOK** callback procedure (THIS IS WRONG), but not **OnGetDepartmentsOK** as required/expected.
For the 'locations' query, also called OnGetLocationsOK, and this is correct.

How to surpass this situation ?
I need each RunQUery to call its own on-success callback procedure.

**Comment by SchneiderInfosystems** [comment]
This was an architectural bug in the library that affected almost all asynchronous calls. The solution found now replaces the storage of the callback functions by hand over the call back function from the request class to the response class.
Thank you for reporting this issue and for your feedback after testing.
