### ISSUE TITLE
[DCC Error] FB4D.Interfaces.pas(126): E2154 Type 'TOnFirebaseResp' needs finalization - not allowed in variant record

### ISSUE THREAD

**Issue by MuratSAPMAZ** [SchneiderInfosystems/FB4D#44]
First of all, thank you for this amazing project. Everything is fine on Windows platform but when I want to compile on Android it gives these errors. RAD Studio 10.3.3

**Comment by SchneiderInfosystems** [comment]
Thank you for reporting this new issue for mobile compiler (ARC) compilers. Can you test again?

**Comment by MuratSAPMAZ** [comment]
Thank you very much, it is perfect now!
