### ISSUE TITLE
Persist IFirestoreDocument in memory

### ISSUE THREAD

**Issue by Loredani68** [SchneiderInfosystems/FB4D#45]
For the work process read / display / change / save, a document (IFirestoreDocument) must be temporarily stored in the memory.
I miss the possibility to create a clone of the read document for later use (e.g change and save an item value).

In the event "OnFirestoreGet" you can use "TFirestoreDocument.CreateFromJSONObj(Docs.Document(c).AsJSON)" to create an IFirestoreDocument based on the read document, but the items will be lost as soon as the event is left, since they're only referenced and not assigned.

Thank you for your efforts

**Comment by SchneiderInfosystems** [comment]
I will check this point later when I extend the current IFirestoreDocument to include automatic object serialization to JSON.

**Comment by SchneiderInfosystems** [comment]
Please check and test this commit a993becc402fccba31b38fde55b217b6e89a5ef6.
