### ISSUE TITLE
Get Online Users

### ISSUE THREAD

**Issue by MuratSAPMAZ** [SchneiderInfosystems/FB4D#46]
Hello, thank you once again for this beautiful project. I want to attract Online users for RealTimeDB. Is there a solution for this or a procedure we can do?

**Comment by SchneiderInfosystems** [comment]
Do you have already seen the videos at my youtube channel 'Schneider Infosystems"?
E.g. https://youtu.be/uqxLGAXoKl0
I prepared this video series for the last International Delphi Developer conference (EKON 23) in Germany where I present a session on FB4D. For regional Delphi Communities I could host also a webcast session. Do not hesitate to send me an email if you are organize such event.

**Comment by MuratSAPMAZ** [comment]
Yes, I have already seen your videos at Youtube. I can do writing "online" and "offline" too, but when the user kills app via swiping kill recents it doesn't handle and I cant write "offline". 

I think my problem is here "the user kills app via swiping kill recents apps" and I can not handle this.

Thank you once again.

**Comment by MuratSAPMAZ** [comment]
Hi, I solved my problem with controlling TApplicationEvent.WillBecomeForeground and TApplicationEvent.EnteredBackground.

Thank you, Thank you, Thank you very much. :)

**Comment by SchneiderInfosystems** [comment]
I completely misunderstood your original question. Please formulate your question in more detail next time.
Thank you for the hint about **_Detecting connection state_**. I will check this system data path _.info/connect_.
