### ISSUE TITLE
Async Upload on Android fails

### ISSUE THREAD

**Issue by gorepj** [SchneiderInfosystems/FB4D#5]
Using the new sample Intro program it is possible to exercise all Storage Upload and Download functions Synchronous and Asynchronous.  They all work perfectly - in Windows.

Excercising the same functions on Android all work except for  Asynchronous Upload.  When Exercising asynchronous upload function the following exceptions occur
EHTTPProtocolException HTTP/1/1 400 Bad Request
followed by
EFirebaseResponse Invalid HTTP Method/URLpair.

**To Reproduce**
1. Create a blank Muti-device application
2. Add the FB4d.DemoFMX.pas form
3. Discard the default main form
4. Edit the program to use hard coded object names etc rather than the openfile dialog methods
5. Compile and run under Windows
6. Enter credentials and login
7. UploadAsynchronous a file (that works fine under Windows)
8. Close application

9. Compile and deploy for Android
10. Login
11. Exercise GetAsynchronous function (for the file you previously uploaded - this works fine) 
12. Exercise UploadAsynchronous - This fails with the above exceptions
(Interestingly UploadSynchronous works fine in Android)

**Expected behavior**
Android Asynchronous Upload behaviour should be identical to that of Windows.

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Delphi Rio
 - Android 7

**Comment by ChristophSchneiderTrihow** [comment]
I'm still trying to reproduce this issue. I assume it is another Delphi RTL issue in the TRestClient component related to the Android platform. Please, can you vote in the embarcadero quality central for RSP-23318 in order that the last reported issue will be solved soon (and I can remove my workaround)?
https://quality.embarcadero.com/browse/RSP-23318

**Comment by gorepj** [comment]
OK - Have Voted
Did you mention you had a workaround?

**Comment by SchneiderInfosystems** [comment]
No, I need first to investigate but I'm pretty sure that this issue is in the underlying delphi component TRestClient. You voted yet for the issue #3 "Storage.UploadFromStream results in error" which also concerns this component.

**Comment by gorepj** [comment]
Yes I have voted

**Comment by medreis** [comment]
To quickly resolve, when calling the Asynchronous method, place a / at the end of the address Storage Bucket Ex. Xxxx.xxxx / and in the synchronous method at address remove, ex Storage Bucket Ex. Xxxx.xxxx

It worked here!

**Comment by SchneiderInfosystems** [comment]
@medreis: I do not understand your workaround. 
The resulting request of an upload is like that:
`Request: rmPOST: https://firebasestorage.googleapis.com/v0/b/<BucketName>/o?uploadType=media&name=<FileName>.txt`
If you place an additonal slash to the <BucketName> then you will use an url ending with `//o`. That canot work.

Unfortunately, I did not find time to write my own test on Android that is why each input to solve this issue is welcome!

**Comment by SchneiderInfosystems** [comment]
I cannot reproduce this issue. I have implemented in the meantime an android application that uses the asynchronous Storage upload properly.
