### ISSUE TITLE
How i get subcollection name 

### ISSUE THREAD

**Issue by XPOSS1312** [SchneiderInfosystems/FB4D#52]
i have structure :
  /mycollection/0MV82xezmrVhn5PJ6gG89aVVTdf1/s4czwD2Jo2Ab3tPGivDo

can i get "s4czwD2Jo2Ab3tPGivDo" with Runquery?

thanks
Allies xposs

**Comment by XPOSS1312** [comment]
Name SubCollection random from CollectionID, and can i get all name SubCollection ?

**Comment by SchneiderInfosystems** [comment]
In the Firstore you use the structure `MyDoc/<DocID>/MySubDocument/<SubDocID>`. If the DocID is known, all SubDocs can be read with `IFirestoreDatabase.Get(['MyDoc', <DocID>, 'MySubDocument']`. You cannot append a subdocument directly under a document. See also the Firestore documentation.

Please note that this is an OpenSource project and you cannot expect free consulting services. For paid consulting services please contact me at www.schneider-infosys.ch.

**Comment by XPOSS1312** [comment]
IFirestoreDatabase.Get(['MyDoc', <DocID>, 'MySubDocument']
 can i get name 'MySubDocument', sir?

**Comment by XPOSS1312** [comment]
thank for follow up sir..
but my case,
IFirestoreDatabase.Get(['MyDoc', <DocID>, 'MySubDocument']
i want to get name collection / "MySubDocument",

example Structure my firestore:
/aktifitasiklan/0MV82xezmrVhn5PJ6gG89aVVTdf1/s4czwD2Jo2Ab3tPGivDo/z37PenGP7of1BxZ62ENr

MySubDocument = s4czwD2Jo2Ab3tPGivDo (random)

thanks

**Comment by SchneiderInfosystems** [comment]
As I understand Firebase, you cannot read the structure information from a client application. In a client application, you need to know your firestore collection / subcollection structure. Please inform me, if you can show me a way, how I can request this information over the Firestore REST API. See the specification from here: https://firebase.google.com/docs/firestore/reference/rest
Check also this discussion here: 
https://stackoverflow.com/questions/47061903/how-to-get-a-list-of-document-ids-in-a-collection-cloud-firestore
Of course, you could write your own firebase function which reads this information with higher privileges (server-side) and return it to your client-application.
