### ISSUE TITLE
Json values 

### ISSUE THREAD

**Issue by rzakfirst** [SchneiderInfosystems/FB4D#54]
Hello. I'm new in json and firebase, i want return json get format form realtime data base

-MPKMpDkyJdq2c6ftItt: {"CompilerVersion":33,"PackageVersion":260,"Product":"Delphi 10.3 Rio","ProductVersion":26}

-MPKZIRnGXSCqG2V3LUq: {"CompilerVersion":33,"PackageVersion":260,"Product":"Delphi 10.3 Rio","ProductVersion":26}

-MPKdv8oH1CconMiQOg1: {"CompilerVersion":"Rzak","DataBaseID":"DATE1","PackageVersion":"5.1","Product":"Bonbon","ProductVersion":"2.10"}

to

{"-MPKMpDkyJdq2c6ftItt":{"CompilerVersion":33,"PackageVersion":260,"Product":"Delphi 10.3 Rio","ProductVersion":26}
,
"-MPKZIRnGXSCqG2V3LUq":{"CompilerVersion":33,"PackageVersion":260,"Product":"Delphi 10.3 Rio","ProductVersion":26}
,
"-MPKdv8oH1CconMiQOg1":{"CompilerVersion":"Rzak","DataBaseID":"DATE1","PackageVersion":"5.1","Product":"Bonbon","ProductVersion":"2.10"}}

Sorry for my bad english, im french. Thank You!

**Comment by SchneiderInfosystems** [comment]
First of all, this is not an issue description but a question or a consulting request. Please use in future for such request the discussion area of FB4D in GitHub.

Do you have seen the `TJSONHelper` class in `FB4D.Helpers.pas`? There are setter methods e.g. TJSONHelpers.SetStringValue which creates JSON objects for writing into the Firestore database. But do you not want to use the Firebase RT DB? I do not understand where you need this conversion in using the RT DB. Please describe the detail in a new discussion thread.
