### ISSUE TITLE
TRealTimeDB.ListenForValueEvents calling ListenEvent and other events without TThread.Queue

### ISSUE THREAD

**Issue by macc2010** [SchneiderInfosystems/FB4D#55]
**Is your feature request related to a problem? Please describe.**
I have a problem with the TRealTimeDB.ListenForValueEvents, when I use this method, I receive the data changed in realtime database in the main thread, so I need to receive it in a thread. In my case, I do not update any UI ( user interface ), I update tables of my database, and the process of updating my database is thread safe, so I am interfering in the main UI thread and I do not need that. 

**Describe the solution you'd like**
I would like to have any properties to decide if I want the call to the events : ListenEvent, OnStopListening, OnError and OnAuthRevoked in the main UI thread ( TThread.Queue ) or without TThread.Queue.

**Describe alternatives you've considered**
publishing  the properties  ListenEventQueued : Boolean, StopListeningQueued : Boolean, ErrorQueued : Boolean and AuthRevokedQueued : Boolean with default values to true, would allow to run the new version of the library without migration problems when any user decide to update to the last version of the library. For example, if ListenEventQueued is true, the library would make the call to TThread.Queue ... fOnListenEvent(EventName, Params, JSONObj) and if ListenEventQueued if false, would make a direct call to the fOnListenEvent(EventName, Params, JSONObj) event without using TThread.Queue.

Thank you.

**Comment by SchneiderInfosystems** [comment]
That's a valuable change request, as I'll be happy to check and incorporate when I get a chance.

**Comment by macc2010** [comment]
Thank you.

**Comment by SchneiderInfosystems** [comment]
You should close this issue not before it is solved ;)

**Comment by macc2010** [comment]
Sorry, I didn't consciously close it, what's more, I was surprised to see it closed. Thank you.

**Comment by SchneiderInfosystems** [comment]
This function is implemented with an additional parameter `DoNotSynchronizeEvents` in `TRealTimeDB.ListenForValueEvents`:
```
    function ListenForValueEvents(ResourceParams: TRequestResourceParam;
      ListenEvent: TOnReceiveEvent; OnStopListening: TOnStopListenEvent;
      OnError: TOnRequestError; OnAuthRevoked: TOnAuthRevokedEvent = nil;
      DoNotSynchronizeEvents: boolean = false): IFirebaseEvent; 
```

Please check this solution and the changed specification at 
https://github.com/SchneiderInfosystems/FB4D/wiki/FB4D-Reference-IRealTimeDB#install-a-listener-for-changes-in-a-json-node

**Comment by macc2010** [comment]
It works like a charm. Thank you very much. :-)
