### ISSUE TITLE
Create TJSONHelper procedures for setting field values contained into a map field of a firestore document.

### ISSUE THREAD

**Issue by macc2010** [SchneiderInfosystems/FB4D#57]
**Is your feature request related to a problem? Please describe.**
It is not a problem, but a novice, until discover how to resolve the problem, loses a lot time searching how to do it.

**Describe the solution you'd like**
I would like that several procedures would be created as helpers in TJSONHelpers for setting values for fields contained into a map field.

**Describe alternatives you've considered**
I have developed my own procedures to help me when I need to set field values of a constructed Firestore document that has a field map and into of this has several fields.

**Additional context**
For example, if I have saved in a firestore document, this data : 

     Doc.AddOrUpdateField(TJSONObject.SetMap('MyMap', [ TJSONObject.SetString('MapStr', 'MapStrValue'),
                                                                                            TJSONObject.SetInteger('MapInt', 324),
                                                                                            TJSONObject.SetBoolean('MapBool', false),
                                                                                            TJSONObject.SetTimeStamp('MapTime', now + 1)]);

And later, I want to read the document and change the value for field "MapInt" from 324 to 325, it would be very useful to have a helper to do it. 

If I want to get the map field "MyMap", I can do : 

     Map := Doc.FieldByName( 'MyMap' );

Why not to have a TJSONHelper procedure like this? :

    Map.SetMapFieldInteger( 'MapInt', 325 ); 

This helper would change the value for the "MapInt" field from 324 to 325.

Adding this procedure to the TJSONHelper : 

procedure TJSONHelper.SetMapFieldInteger( const aFieldName : string; const aValue : Integer );
var
  Obj: TJSONObject;
begin
  Obj := GetValue<TJSONObject>('mapValue').GetValue<TJSONObject>('fields'); 
  if Obj <> nil then
  begin
    Obj.RemovePair( aFieldName );
    Obj.AddPair( TJSONObject.SetInteger( aFieldName, aValue ) );
  end;
end;

would make more intuitive that to write several lines only to update one submap field value. 

It would very useful to create the following procedures : SetMapFieldString, SetMapFieldTimeStamp, SetMapFieldBoolean ... etc. 

Perhaps there is a simple solution, but I have not seen. 

Thank you.

**Comment by SchneiderInfosystems** [comment]
I will check this idea soon. 

Do you know the PatchDocument method? With this approach, you will never merge fields from an existing document with the changed ones.

**Comment by macc2010** [comment]
I had not thought in the PatchDocument method, I will try to use it. 

Thank you very much. :-)

**Comment by ichsansy2901** [comment]
hi sir how to set the value Doc.AddOrUpdateField (TJSONObject.SetArray ('test'),[TJSONObject.SetStringValue('testing')based on ListBox1.ItemByIndex (c)

**Comment by SchneiderInfosystems** [comment]
@ichsansy2901: Please check FB4D.DemoFmx at TfmxFirebaseDemo.btnInsertOrUpdateDocumentClick:
`Doc.AddOrUpdateField(TJSONObject.SetArray('test',[
             TJSONObject.SetStringValue('testing'),
             TJSONObject.SetStringValue('...`
Please discuss such a question next time in the discussion forum to avoid confusion with the existing change request from macc2010. Thank you
https://github.com/SchneiderInfosystems/FB4D/discussions

**Comment by macc2010** [comment]
I have left this night the program running and when I have comeback to the office this morning I have seen an access violation in the THttpClient trying to write to the stream, so the problem has not been still resolved. 

I can imagine that I am not the only one person who can have this problem. 

As I have tested my modifications, and I am still testing the modifications before production use, and as I am implicated in to send to you any error that I see in this modifications, I propose to you to have a conditional compiler definition to resolve this problem. 

Can you see what is your opinion about this source code? : 

[Source files modified 20210519.zip](https://github.com/SchneiderInfosystems/FB4D/files/6507602/Source.files.modified.20210519.zip)

As you can see, all the applications that would use this source code would run exactly like they have done until now, but if you remove the dot to the {.$DEFINE FIRESTORELISTENER_WINDOWS_AV_FIX} conditional define, the fix that I have tested in Windows projects would be applied. 

I suppose that it would be useful for someone who would have the same problems that I have had, and the solution to this, only would suppose to remove the dot of the new conditional define.

My solution is only tested in Windows projects ( fmx and vcl ) and in Delphi 10.4.2, so because of that I have added this conditions before the {.$DEFINE}.

**Comment by dide2k** [comment]
I agree this would be a very usefull feature enhancement to manage map fields ! To keep things aligned I would introduce 'AddorUpdateMapField' on the document level ( instead of creating a new setmapxxxx for every possible type ). Or, ideally it also handles nested map fields automatically based on the 'fieldname' (path) contaning '.' or not. e.g. 'AddOrUpdateField' with fieldname 'map.nestedmap.counter' should add or update the counter field in the nestedmap...

**Comment by SchneiderInfosystems** [comment]
I implemented a late solution today. To be able to directly address a field in a map, there is now this overloaded function:

    IFirestoreDocument = interface(IInterface)
      function GetMapValue(const FieldName, SubFieldName: string): TJSONObject;
      overload;

After creating a complex documentin the DemoFB4D application ,  you can address the `MapStr` in `MyMap` with this new function as follows:

`Doc.GetMapValue('MyMap', 'MapStr').GetStringValue `
