### ISSUE TITLE
Bug in the procedure TRealTimeDB.OnRecData, TStringStream.Create has not UTF8 encoding.

### ISSUE THREAD

**Issue by macc2010** [SchneiderInfosystems/FB4D#58]
**Describe the bug**
In the procedure TRealTimeDB.OnRecData, when the TStringStream is created, it has ANSI encoding ( the default for TStringStream ) and the reading of the data is transformed to ANSI. In other sites of the library there is not problem because you assign UTF8 when you use TStringStream.Create( xxx.ToJSON ) and ToJSON return a TEncoding.UTF8. 

**To Reproduce**
1. Go to Realtime database and save any data with an special character, for example with accents, for example, the word "Acción" in spanish language. 
2. Use ListenForValueEvents and see the data read, instead of the word "Acción", you will see other characters.

**Desktop (please complete the following information):**
 - OS: Windows
 - Version : Delphi 10.3 update 3.

** Solution : 
In the procedure TRealTimeDB.OnRecData, change : 

    ss := TStringStream.Create;

By : 

        ss := TStringStream.Create('',TEncoding.UTF8);

Thank you.

**Comment by SchneiderInfosystems** [comment]
Thank you for reporting this important issue.

**Comment by SchneiderInfosystems** [comment]
Please check the solution carefully and send feedback.

**Comment by macc2010** [comment]
I will test the new code and send the results. Thank you for the fast resolution.

**Comment by macc2010** [comment]
I have tested the solution and works like a charm. Thank you very much. :-)
