### ISSUE TITLE
Enable / Disable / Delete User

### ISSUE THREAD

**Issue by gorepj** [SchneiderInfosystems/FB4D#6]
Can you please add procedures or functions to delete a User and (less important) disable / enable a user

**Comment by gorepj** [comment]
Hello Christoph. The reason for my request is really to do with Data Protection Legal Compliance. European data protection regulation requires "right to be forgotten" amongst other things.  So I would like to enable any User to delete the account themselves by clicking a button.  This way, addressing your point above, the Users delete themselves and don't require an Admin/Superuser account

**Comment by SchneiderInfosystems** [comment]
Ok, make sense. I will implement this self delete function soon.

**Comment by gorepj** [comment]
OK thank you Christoph

**Comment by SchneiderInfosystems** [comment]
Solved with commit 8e03f8fb2ee8f2655d1a83222e182a3a518d54de
