### ISSUE TITLE
Callback-Method for DeleteDoc not working

### ISSUE THREAD

**Issue by ValidationFailed** [SchneiderInfosystems/FB4D#63]
**Describe the bug**
Callback-Method for Firestore-DeleteDoc never gets executed

**To Reproduce**
1. Open the DemoFB4D-Project
2. Create a breakpoint at line 1123 / procedure "OnFirestoreDeleted"
3. Start the demo program (in debug mode)
4. Delete a Document -> the program won't stop at the breakpoint.

**Expected behavior**
The method set as callback method should be executed after successfully deleting a document. 

**Desktop:**
 - OS: Windows 10, 32 Bit

**Additional context**
It might also be problem on my end or created by me. I just discovered that the code in my OnDeleteDoc is never being executed. Afterwards, I tried deleting something with the demo provided and noticed the same issue.

Nonetheless, I want to thank you for your hard work on this library. I'd like to think that I learnt a lot just by having a look at your code. 
Also, thank you for the excellent sample projects and wiki you provided us with.

Edit: Added 32 Bit to OS
Edit2: I just (accidently) found out that, by providing an invalid path, the "OnFirestoreError"-procedure is being executed. There's just nothing happening on success.

**Comment by SchneiderInfosystems** [comment]
Thank you for this valuable bug report.  

This problem was present since the correction of issue #43 and only platforms without AUTOREFCOUNT were affected. 

If you are satisfied with my response time and the correction I am happy about your star for this repo ;)

**Comment by ValidationFailed** [comment]
Thanks a lot for the quick response and fix!
Of course I star'd this repository. :)
Have a great day!
