### ISSUE TITLE
Missing Realtime Database location: Belgium (europe-west1) [beta]

### ISSUE THREAD

**Issue by koufopoulosf** [SchneiderInfosystems/FB4D#67]
When someone creates a Firebase project (e.g. named "myproject"), the following two Realtime Database options are provided:

- Realtime Database location: United States (us-central1) 
-  `https://myproject-default-rtdb.firebaseio.com/`

or

- Realtime Database location: Belgium (europe-west1) [beta]
-  `https://myproject-default-rtdb.europe-west1.firebasedatabase.app/`

...

But!!

In [/Source/FB4D.RealTimeDB.pas](https://github.com/SchneiderInfosystems/FB4D/blob/d423161fe177224fb0991fcfef82e3acb135a334/Source/FB4D.RealTimeDB.pas#L143) file, the following const is specified: ` GOOGLE_FIREBASE = 'https://%s.firebaseio.com';`

_**As a result,**_ projects under _Realtime Database location: Belgium (europe-west1) [beta]_, do not have access to FB4D.RealTimeDB features.

**Comment by gorepj** [comment]
Ah,
I am getting the same problem.  Projects I created a year or two ago work
fine with Real Time Database but now new ones do not.  It must be the same
problem.
Regards
Peter

**Comment by koufopoulosf** [comment]
Also, let me note the following misconception:

The "Project ID" requested field on DemoFB4D, should not be "myproject" as it is displayed on firebase (/project/#{myproject}/settings/general)

but it should be "myproject-default-rtdb" in order to work.


Kind regards,
Filippos K.

**Comment by SchneiderInfosystems** [comment]
Indeed, there is a change in the Realtime DB creation. Currently you can create an instance as follows: `TRealTimeDB.Create('<ProjectID>-default-rtdb.europe-west1', Auth); `
Access via ClassFactory `TFirebaseConfiguration` to a new RT DB is currently not possible. I will have to introduce one or two new configuration fields.

**Comment by SchneiderInfosystems** [comment]
Please test the new solution carefully.

@gorepj: Please inform me next time sooner. Such changes in the Firebase are difficult to detect.

**Comment by gorepj** [comment]
Thank you Christoph,
and I can confirm all is working correctly  now; old and new.
Regards
