### ISSUE TITLE
Android - Automatic Login not working(?)

### ISSUE THREAD

**Issue by koufopoulosf** [SchneiderInfosystems/FB4D#68]
Hello all!

I used both FirestoreSimpleChat & RTDB_PerUserReadWrite project samples (that utilize FB4D.SelfRegistrationFra) on Android 32-bit and Windows 64-bit. While automatic login works on my desktop (Windows 64-bit), on my device (Android 32-bit), instead of automatic logging in, it starts again from the beginning.

Is Automatic Login supposed to work only on desktop applications? Am I missing something? If yes, what should I do to make it work on mobile versions?

Thanks in advance!

Kind Regards,
koufopoulosf

**Comment by koufopoulosf** [comment]
Fixed.

Let's take the case of FirestoreSimpleChat.

```
procedure TfmxChatMain.FormClose(Sender: TObject; var Action: TCloseAction);
begin
  SaveSettings;
  FreeAndNil(fConfig);
end;
```

Same applies to RTDB_PerUserReadWrite.

```
procedure TfmxMain.FormClose(Sender: TObject; var Action: TCloseAction);
begin
  SaveToken;
end;
```


Saving Tokens/Settings on FormClose has no effect on mobile versions, thus they should be removed from FormClose and added somewhere else inside the code.

For example, in the case of RTDB_PerUserReadWrite, I added the SaveToken here:

```
procedure TfmxMain.OnUserLogin(const Info: string; User: IFirebaseUser);
begin
  fUID := User.UID;
  lblUserInfo.Text := Format(rsUserInfo, [User.EMail, fUID]);
  StartListening;
  SaveToken;
end;
```


I'm not sure whether it's appropriate to use the SaveToken (or SaveSettings) e.g. OnUserLogin instead of FormClose, so I'd like a confirmation at this one. Tested on Android 32-bit device.

**Comment by SchneiderInfosystems** [comment]
This issue is solved now properly by introducing TFirebaseAuthentication.InstallTokenRefreshNotification.
