### ISSUE TITLE
Sample using QueryFilter

### ISSUE THREAD

**Issue by wibitecnologia** [SchneiderInfosystems/FB4D#7]
Hi, Have a sample using QueryFilter ?

thanks.

**Comment by SchneiderInfosystems** [comment]
Unfortunately, my current workload has not allowed to finish the writing in the reference GUID but I have yet addded the requested describtion here 
https://github.com/SchneiderInfosystems/FB4D/wiki/FB4D-Interface-Reference#interface-istructuredquery
Is this description understandable for a start? 
The QueryForCompositeFilter allows to add several IQueryFilter by combine it with the logical operator and. 
Thank you for any hint concerning the existing reference guide.

**Comment by SchneiderInfosystems** [comment]
There are additional explanation added in the chapter Interface IStructuredQuery and chapter Interface IQueryFilter. Do not hesitate to ask again if points are still unclear.
