### ISSUE TITLE
Firestore listener, monitor changes in all the documents of a subcollection

### ISSUE THREAD

**Issue by macc2010** [SchneiderInfosystems/FB4D#78]
**Is your feature request related to a problem? Please describe.**
For me yes, I need to monitor changes of documents in a subcollection.

**Describe the solution you'd like**
In the method TFirestoreDatabase.SubscribeQuery, add a new parameter to indicate the document path.

**Describe alternatives you've considered**

I have modified the source code to add to IFirestoreDatabase.SubscribeQuery, TFirestoreDatabase.SubscribeQuery and TFSListenerThread.SubscribeQuery the parameter : Document_Path.

The code modified is : 

```
function TFirestoreDatabase.SubscribeQuery(Query: IStructuredQuery;
  OnChangedDoc: TOnChangedDocument; OnDeletedDoc: TOnDeletedDocument; const Document_Path : string = ''): cardinal;
begin
  result := fListener.SubscribeQuery(Query, OnChangedDoc, OnDeletedDoc, Document_Path);
end;

function TFSListenerThread.SubscribeQuery(Query: IStructuredQuery;
  OnChangedDoc: TOnChangedDocument; OnDeletedDoc: TOnDeletedDocument; const Document_Path : string = ''): cardinal;
var
  Target: TTarget;
  JSONobj: TJSONObject;
begin
  if IsRunning then
    raise EFirestoreListener.Create(
      'SubscribeQuery must not be called for started Listener');
  Target.TargetID := (fTargets.Count + 1) * 2;
  Target.TargetKind := TTargetKind.tkQuery;
  JSONobj := Query.AsJSON;
  if Document_Path = '' then
    JSONobj.AddPair('parent', fDatabase + '/documents')
  else
    JSONobj.AddPair('parent', fDatabase + '/documents/' + Document_Path);
  Target.QueryJSON := JSONobj.ToJSON;
  Target.DocumentPath := '';
  Target.OnChangedDoc := OnChangedDoc;
  Target.OnDeletedDoc := OnDeletedDoc;
  fTargets.Add(Target);
  result := Target.TargetID;
end;

```
My structure is : main_collection1/document1/subcollection1 and into the subcollection1 I have several documents. If I want to listen for changes  in the documents of subcollection1, I can do : 

`fDatabase.SubscribeQuery(TStructuredQuery.CreateForCollection('subcollection1), OnFSChangedDocInCollection, OnFSDeletedDocCollection, 'main_collection1/document1');
`

It seems that it works, I have tested it. 

Thank you.

**Comment by SchneiderInfosystems** [comment]
Thank you for this valuable hint and the good documentation!

Originally I thought that can be passed in the `StructuredQuery`. But this is not the case. I have now practically adopted your suggestion and only adjust the path type so that it is applied as an array of strings identical as in `SubscribeDocument`. 

Can you test the solution and give me some feedback, so we can close this issue?

Thanks for the star the repo, if you like FB4D.

**Comment by macc2010** [comment]
Hello, I have tested the solution and it works like a charm. 

Thank you very very much, best regards. :-)
