### ISSUE TITLE
try finally in TFSListenerThread.Execute after fClient := THTTPClient.Create

### ISSUE THREAD

**Issue by macc2010** [SchneiderInfosystems/FB4D#79]
**Is your feature request related to a problem? Please describe.**
Not, it is not a problem, but could to be at any situation. 

**Describe the solution you'd like**
I would like to protect the pair of create and destroy of the fClient object in TFSListenerThread.Execute.

**Describe alternatives you've considered**
Simply, I have seen that after fClient := THTTPClient.Create; there is a try except block, but after this block there is a call to the OnAuthRevoked that could to raise an exception and leave without execution the line FreeAndNil(fClient). 

I would like to thank to Christoph Schneider for his generosity in making this library open source and for the effort he has made. 

Thank you very much.

**Comment by SchneiderInfosystems** [comment]
Thank you for this valuable hint.
