### ISSUE TITLE
Get with auth

### ISSUE THREAD

**Issue by leonardoaa** [SchneiderInfosystems/FB4D#8]
Hi my friends...

Is possible request a data with auth? When I request data with this parameters on my project, appears the message: Get  failed: Permission denied (Get is an example, but path, put, delete have same error)

my firebase rules:

{
  "rules": {
    "users": {
      "$uid": {
        ".read": "$uid === auth.uid",
        ".write": "$uid === auth.uid"
      }
    }
  }
}

tks a lot!

Leo

**Comment by SchneiderInfosystems** [comment]
Hi Leo

Yes, of course it is possible to restrict the access to data in the Firebase Real time DB by using the UID. 
Your written rule requires a data structures of /users/<UID>/ for the top node of the user specific data.

Do you have read this description? 
https://github.com/SchneiderInfosystems/FB4D/wiki/Getting-Started-with-FB4D#security-in-firebase-setup-the-access-rules?

It seems for me that you struggle with the security rules concept of Firebase. For helping I would need more information. How do you built the data structure in the Firebase? For that show me your access code.

Please send me such information by mail but also be aware that I cannot spend hours of free consulting.

regards. 
Christoph
www.schneider-infosys.ch

**Comment by leonardoaa** [comment]
Perfect!

I tried with this structure and now it works!

this is my rules:

[image: image.png]
...and my firebase structure, after modification:

[image: image.png]

in demo app, now using tihs way:
[image: image.png]

tks a Lot!!! this project is awesome!!!




*Leonardo Augusto de Almeida*
leonardo.aug@gmail.com


Em sex, 8 de mar de 2019 às 04:27, Christoph Schneider <
notifications@github.com> escreveu:

**Comment by SchneiderInfosystems** [comment]
Thank you too! 

If you see that anything is unclear written or wrong, do not hesitate to write me again.
