### ISSUE TITLE
Bug in function TJSONHelpers.GetArraySize: integer;

### ISSUE THREAD

**Issue by macc2010** [SchneiderInfosystems/FB4D#80]
**Describe the bug**
When an array field has no elements, the helper function TJSONHelpers.GetArraySize fail.

**To Reproduce**
1. Go to 'Firestore console
2. Create a collection and a document
3. Create an array field into the document and leave it without items.
4. Open DemoFB4D.dpr and run it and in the Firestore tab, try to get the document, a exception will be raised.

**Expected behavior**
TJSONHelpers.GetArraySize should to return 0 for the field and not to raise a exception.

I have modified the function to avoid the exception : 

```
function TJSONHelpers.GetArraySize: integer;
var
  Obj : TJSONObject;
  Val : TJSONValue;
begin
   //result := GetValue<TJSONObject>('arrayValue').GetValue<TJSONArray>('values').Count;
   Obj := GetValue<TJSONObject>('arrayValue');
   Val := Obj.FindValue('values');
  if Val <> nil then
    Result := TJSONArray(Val).Count
  else
    Result := 0;
end;

```
Thank you.

**Comment by SchneiderInfosystems** [comment]
Thank you for checking this border case and for the good proposal!
