### ISSUE TITLE
Android + FB4D.OAuth = Undeclared identifier: 'ITokenJWT'

### ISSUE THREAD

**Issue by kazuser** [SchneiderInfosystems/FB4D#81]
1. Create a brand new project and add the "FB4D.OAuth" to "uses"
2. Set "Android 64-bit" as a target platform
3. Try to deploy

![FB4D OAuth](https://user-images.githubusercontent.com/3335273/115105979-dcddfd00-9f83-11eb-9d18-3c95b505a5ae.gif)

**Comment by kazuser** [comment]
Well, I temporarily fixed this by copying the block of the same name from "FB4D.Interfaces" but I doubt that this is the right solution 😶

Before:
![before](https://user-images.githubusercontent.com/3335273/115106263-9093bc80-9f85-11eb-8481-1c719c96d86e.png)

After:
![after](https://user-images.githubusercontent.com/3335273/115106270-96899d80-9f85-11eb-8c52-4053b346e177.png)

**Comment by SchneiderInfosystems** [comment]
Why you don't want to use the `FB4D.Interface.pas` in your project?

This is the central unit that all projects require when using functions of FB4D.
