### ISSUE TITLE
Memory leak in TFirestoreDatabase with  fListener / TFSListenerThread

### ISSUE THREAD

**Issue by dide2k** [SchneiderInfosystems/FB4D#82]
**Describe the bug**
The default delphi IDE memoryleak detector ( ReportMemoryLeaksOnShutdown := true; ) reports a memory leak when a IFirestoreDatabase interface is created and freed ( automatically ) when the embedded listener was never started.
( and thus not terminated and freed automatically ? )
![DelphiCapture](https://user-images.githubusercontent.com/63043376/115454274-e5069880-a220-11eb-8f85-2c119859fb9b.JPG)

**To Reproduce**
Using the FB4D sample application DemoFB4D :
1. Login anonymously
2. Do a firestore database CREATE DOCUMENT
3. Close the form

**See Screenshots**

( Windows 64 in DEBUG )

**Comment by SchneiderInfosystems** [comment]
Thank you for this important finding! 

Be aware that with Delphi 10.3.3 and the former version, there can be still a memory leak and delayed application stop because of RSP-20827.

Thank you for testing my solution carefully and if possible on different platforms.
