### ISSUE TITLE
Memory leak in TFirestoreDocument AddOrUpdateField ( both overloaded versions )

### ISSUE THREAD

**Issue by dide2k** [SchneiderInfosystems/FB4D#83]
**Describe the bug**
The default delphi IDE memoryleak detector ( ReportMemoryLeaksOnShutdown := true; ) reports a memory leak when an existing IFirestoreDocument field is changed ( or added and then updated if not exisited yet )

In the code , an existing pair is first removed before added again     
 `391  FieldsObj.RemovePair(FieldName);`
 
But TJSONObject.RemovePair is a function that returns the removed TJSONPair. It still needs to be freed if no longer required.
so I think this should be
 `391  FieldsObj.RemovePair(FieldName).Free;`

**To Reproduce**

Run the following code and close the form 

procedure TForm1.Button2Click(Sender: TObject);
var
 fFirestoreDocuments : IFirestoreDocuments ;
 fAuth : IFirebaseAuthentication ;
 fDatabase: IFirestoreDatabase;

begin

  fAuth :=  TFirebaseAuthentication.Create('YourAPIKey');
  fAuth.SignInAnonymouslySynchronous;

  fDatabase := TFirestoreDatabase.Create('YourProjectID', fAuth);

  fFirestoreDocuments := fDatabase.GetSynchronous(['YourExistingCollection']);
  if fFirestoreDocuments.Count > 0 then begin
   fFirestoreDocuments.Document(0).AddOrUpdateField(TJSONObject.SetString('TEST' , 'Test1' ));
   fFirestoreDocuments.Document(0).AddOrUpdateField(TJSONObject.SetString('TEST' , 'Test2' ));
  end;

end;

**Screenshots**
![DelphiCapture2](https://user-images.githubusercontent.com/63043376/115527512-672ea580-a291-11eb-89e5-15f06cb13fc1.JPG)

**Desktop (please complete the following information):**
 - Windows OS 64 debug

Note, please also review the difference in the following line between the 2 overloaded versions 
  fFields[Ind].Obj := Val.Clone as TJSONObject; ( in AddOrUpdateField(  const FieldName: string;  Val: TJSONValue) )
versus
  fFields[Ind].Obj := Val as TJSONObject; ( in AddOrUpdateField( Field: TJSONPair) ) 

I believe the cloned tjsonobject is also never freed ( as it's not part of the root json object ).
In these functions , the 'val' parameter is typed as TJSONValue, but internally it's type casted to TJSONObject in the line above. Maybe better type it also as TJSONObject in the function params then.

**Comment by SchneiderInfosystems** [comment]
Thank for this finding!
