### ISSUE TITLE
get pure json from document FireStore

### ISSUE THREAD

**Issue by ch4rl3s** [SchneiderInfosystems/FB4D#9]
Is there any way to get the pure json from the Fireastore document without MapValue like doubleValue, integerValue.
from
"produto":{"integerValue":"22"}
to
"produto":"22"

thanks;

**Comment by SchneiderInfosystems** [comment]
Hi 
The Firebase itself does not offer a such flat json.
What you can do is to parser the document field by field and write your own JSONObject new.

In the newest commit I have added alot of new getter methods for the getting fields from the document. See the get button in DemoFB4D in the Firestore tab and analyse is after Insert a document by checking "create complex doc".

Is that helpful for you?

Regards
Christoph
