### ISSUE TITLE
FB4D.Helpers.pas, bad use of conditional compilation?

### ISSUE THREAD

**Issue by macc2010** [SchneiderInfosystems/FB4D#95]
**Describe the bug**
If I create a vcl project, the TFirebaseHelpers.Log is called by certain parts of the library and when it is executed, there are several problems : 

1) FMX.Types and FMX.Forms are declared in the uses clause of the FB4D.Helpers.pas, be the project, VCL, or FMX.

2) When TFirebaseHelpers.Log is called with the msg parameter, FMX.Types.Log.d(msg, []) is called and in a VCL project I do not want to call FMX routines. 

3) TFirebaseHelpers.SleepAndMessageLoop is calling to Application.ProcessMessages from TApplication declared in FMX.Forms, I do not know how is the bearing of a vcl application calling this FMX routines, it could be a possible source of problems, it should to call Application.ProcessMessages from VCL.Forms. I wonder if I am having problems with access violation caused by the FMX routines when TFSListenerThread.StopListener is calling the TFirebaseHelpers.SleepAndMessageLoop(5) ( who is calling to the Application.Processmessages of FMX in a VCL application ).

**To Reproduce**
Compile any application with vcl target to see the problem.

**Possible solution**
I think that it should to be used the Defined compiler directive instead of the Declared compiler directive. 

As I read in the documentation in this address : 

http://docwiki.embarcadero.com/RADStudio/Sydney/en/IF_directive_(Delphi) 

I can only see that when it is used : {$IF Declared(FMX)}, it should to be at any .pas files declared in the uses clause an identifier that would be FMX ( I can not see it in the path of Delphi sources : "C:\Program Files (x86)\Embarcadero\Studio\21.0\source" ), an example would be : 

    const FMX = 1;

If I declare this constant and I write :
   {$IF Declared(FMX)}
      ShowMessage( 'FMX' );
   {$ENDIF}

A message 'FMX' is shown in my application.  But if I remove the line const FMX = 1, the message is not shown. 

That makes a difference with the    {$IF Defined(VCL)} for example. If I go to Project -> Options -> Delphi compiler -> and add a conditional compiler named VCL, then, if I write : 

{$IF Defined(VCL)}
  ShowMessage( 'VCL' );
{$ENDIF}

A message 'VCL' is shown in my application.  

I see one solution, for the VCL projects, to declare the VCL compiler directive. 

For existing projects it would not be a problem, because the VCL compiler directive is not declared ( probably ) and the programs will call to the FMX routines, so the behaviour is not altered. But if the programmer in a VCL application, Project -> Options -> Delphi compiler -> and add a conditional compiler named VCL, then FB4D.Helpers.pas should to make sense of it. 

I propose a solution that would be this : 

[FB4D.Helpers.zip](https://github.com/SchneiderInfosystems/FB4D/files/6466381/FB4D.Helpers.zip)

You can see the  CONSOLE compiler directive here : http://docwiki.embarcadero.com/RADStudio/Sydney/en/Conditional_compilation_(Delphi)

Perhaps there is a solution that I do not know, but is the only that I have seen to solve the problem.

Thank you.

**Comment by SchneiderInfosystems** [comment]
Do you have added $(FrameworkType) as compiling conditional?

Please read the wiki page
https://github.com/SchneiderInfosystems/FB4D/wiki/Project-settings-for-FB4D

Can you close this issue if your problem is solved with this hint?

**Comment by macc2010** [comment]
I had no idea that $(FrameworkType) solved the problem, sorry I forgot that in project settings.

Please, read this : https://www.ideasawakened.com/post/writing-cross-framework-code-in-delphi

I have added $(FrameworkType) in my project options : 

![FB4D_compiler_options](https://user-images.githubusercontent.com/34898210/118495795-d75f0880-b723-11eb-9550-0b855fad38aa.png)

And after that, I have rebuild the project and the execution of the FB4D.helpers Log is : 

![FB4D Helper_execution](https://user-images.githubusercontent.com/34898210/118496365-5c4a2200-b724-11eb-8898-71f5e4103535.png)

I think that there is something bad, I am using FB4D.helpers.pas from github. 

In fact , FMX.Types, is still compiled and added in the uses.

![FB4D Helper_compilererror](https://user-images.githubusercontent.com/34898210/118497155-19d51500-b725-11eb-8415-283a31189d3a.png)

Thank you.

**Comment by macc2010** [comment]
If I replace Declared by Defined in the source code of FB4D.Helpers.pas, all works ok.

[FB4D.Helpers.zip](https://github.com/SchneiderInfosystems/FB4D/files/6494184/FB4D.Helpers.zip)

**Comment by macc2010** [comment]
My project has it in the .dproj : 

![project](https://user-images.githubusercontent.com/34898210/118499739-818c5f80-b727-11eb-966d-06bc65f29d54.png)

**Comment by SchneiderInfosystems** [comment]
`{$IF Declared(VCL)}` works in different projects I have compiled with Delphi 10.4.2.

Two points to consider:
- You have defined $(FrameworkType) in the Debug build configuration? Write this conditional into Target "All Configurations" to ensure you can build also the release.
- Probably you need to clean and rebuild your project after changing these project settings.

Can you confirm, that my original solution is working too?

The trick with the conditional `FireMonkeyVersion` does not work for FB4D because in case you write a service or a console application, you do have neither VCL nor FMX but this is handled by the current solution ;)

**Comment by macc2010** [comment]
To avoid confusion, I have created a new project and defined in Project -> Options -> Delphi compiler -> Conditional defines : $(FrameworkType). You can see here : 

![FB4D_compiler_options](https://user-images.githubusercontent.com/34898210/118560501-de106e80-b769-11eb-841b-64ee9464a255.png)

After this, I have rebuild the project with the opcion Project -> Rebuild all projects. 

I have attached the sample project : 

[TestDeclaredDefined.zip](https://github.com/SchneiderInfosystems/FB4D/files/6497040/TestDeclaredDefined.zip)

With the FB4D.helpers.pas from github. 

But when I debug and stop the debugger in the line : 

![project](https://user-images.githubusercontent.com/34898210/118560765-4d865e00-b76a-11eb-8565-4580dee1e883.png)

I press F7 and see it : 

![FB4D Helper_execution](https://user-images.githubusercontent.com/34898210/118560893-7eff2980-b76a-11eb-9202-902aa0112303.png)

It is stranger, the code executes FMX.Types.Log.d, I do not know if I have something bad in my Delphi installation, can you test the project that I have attached and check that FMX.Types.Log.d is NOT executed?. 

Thank you.

**Comment by macc2010** [comment]
in this version of the new project, it is more clear the different behaviour between Declared and Defined : 

[TestDeclaredDefined.zip](https://github.com/SchneiderInfosystems/FB4D/files/6497153/TestDeclaredDefined.zip)

The result is different : 

![project](https://user-images.githubusercontent.com/34898210/118563290-950ee900-b76e-11eb-8de1-e2962ed462cc.png)

**Comment by macc2010** [comment]
I think that Defined works as expected, but Declared not.

**Comment by SchneiderInfosystems** [comment]
I can see the differences in your test project, but I do not understand why my solution in FB4D helpers worked before in different project all the time.

Also the specification from Embarcadero was not clear to me, but I see that defined is not wrong.
http://docwiki.embarcadero.com/RADStudio/Sydney/en/IF_directive_(Delphi)

So I decided to change to defined in the hope, this prevents such troubles in the future.

**Comment by macc2010** [comment]
Thank you very much.
