### ISSUE TITLE
Warning about {$IFDEF WINDOWS} use.

### ISSUE THREAD

**Issue by macc2010** [SchneiderInfosystems/FB4D#98]
I do not know if it can be a bug, but in several .pas files I have seen the use of {$IFDEF WINDOWS}, for example in FB4D.FireStore.Listener.pas :

  {$IFDEF WINDOWS}
  EventName := 'FB4DFSListenerGetFini';
  {$ELSE}
  EventName := '';
  {$ENDIF} 

As you can see in http://docwiki.embarcadero.com/RADStudio/Sydney/en/Conditional_compilation_(Delphi), WINDOWS conditional compilation does not exists, exists MSWINDOWS.

In Delphi source code, for example : "C:\Program Files (x86)\Embarcadero\Studio\21.0\source\Indy10\System\IdStackConsts.pas", it is used {$IFDEF WINDOWS} because WINDOWS has been defined in "C:\Program Files (x86)\Embarcadero\Studio\21.0\source\Indy10\System\IdCompilerDefines.inc", and this .inc has been included in the .pas with a {$I IdCompilerDefines.inc}.

But in FB4D, I have not seen that the WINDOWS conditional compiler variable have been defined, so the code with {$IFDEF WINDOWS} is not executed, I do not know if it is affecting to something in the code.

**Comment by SchneiderInfosystems** [comment]
Thank you for this valuable hint. It is solved now.

**Comment by macc2010** [comment]
Thanks to you, happy to help.
